version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: yarn install || npm i
      - run: cd stf-core && yarn eslint
      - run: cd stf-api && yarn eslint
      - run: cd stf-player && yarn eslint && yarn build
workflows:
  main:
    jobs:
      - build
