version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
      - image: circleci/mongo:4.2.0
    steps:
      - checkout
      - run:
          name: Install dependency
          command: yarn install
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Api
          command: cd stf-api && yarn test
      - run:
          name: Player
          command: cd stf-player && yarn eslint && yarn build
      - run:
          name: Raspberry Pi
          command: cd stf-rasp && yarn install && yarn eslint
      - run:
          name: Admin
          command: cd stf-admin && yarn eslint && yarn build
      - run:
          name: Core
          command: cd stf-core && yarn eslint
      - run:
          name: Admin-desktop
          command: cd stf-admin-desktop && yarn install && yarn eslint && yarn pack
workflows:
  main:
    jobs:
      - build
