version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
      - image: circleci/mongo:4.2.0
        port: 27017:27017
    steps:
      - checkout
      - run: yarn install || npm i
      - run:
          name: Waiting for Mongo
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run: cd stf-core && yarn eslint
      - run: cd stf-api && yarn test
      - run: cd stf-player && yarn eslint && yarn build
workflows:
  main:
    jobs:
      - build
