#
# https://docs.netlify.com/configure-builds/file-based-configuration
#

[build]
    base = "packages/admin/"
    publish = "build/"
    command = "yarn build"
#    ignore = "git diff --quiet master ."
