name: Continuous Integration
on: [pull_request]

env:
  NODE_VERSION: '12.x'

jobs:
  Validate:
    name: 'Validate Pull Request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages
    steps:
      - name: 'Git checkout'
        uses: actions/checkout@v2
      - name: 'Use cached node_modules'
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: 'Install dependency'
        run: yarn install --frozen-lockfile
      - name: 'Prettier'
        run: cd .. && yarn prettier
      - name: 'Start MongoDB'
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
          mongodb-replica-set: test-stf-db
      - name: 'Install dependency'
        run: yarn install --frozen-lockfile
      - name: 'Api'
        run: cd api && yarn lint && yarn test
      - name: 'Player'
        run: cd player && yarn lint && yarn build
      - name: 'Admin'
        run: cd admin && yarn lint && yarn build
      - name: 'Core'
        run: cd core && yarn lint
      - name: 'UI Components'
        run: cd ui-components && yarn lint && yarn build && yarn build:storybook
      - name: 'Table'
        run: cd table && yarn lint
      - name: 'Table Manager'
        run: cd table-manager && yarn lint
