name: Continuous Integration
on: [pull_request]

jobs:
  Web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages
    steps:
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
          mongodb-replica-set: test-stf-db
      - name: Install dependency
        run: yarn install
      - name: Api
        run: cd api && yarn test
      - name: Player
        run: cd player && yarn eslint && yarn build
      - name: Admin
        run: cd admin && yarn eslint && yarn build
      - name: Core
        run: cd core && yarn eslint

  Raspberry:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/raspberry
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependency
        run: yarn install
      - name: Raspberry Pi
        run: yarn eslint

  Electron:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/admin-desktop
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependency
        run: yarn install
      - name: ESLint
        run: yarn eslint
#  Electron:
#    strategy:
#      matrix:
#        os: [macos-latest, ubuntu-latest, windows-latest]
#    runs-on: ${{ matrix.os }}
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v1
#        with:
#          node-version: 14
#      - name: Install dependency
#        run: cd admin-desktop && yarn install
#      - name: ESLint
#        run: cd admin-desktop && yarn eslint
#      - name: Pack All
#        run: yarn electron:pack:all
