name: PR
on: [pull_request]

jobs:
  pr:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependency
        run: yarn install
