name: PR Raspberry
on: [pull_request]

jobs:
  Pull-Request:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependency
        run: yarn install
      - name: Raspberry Pi
        run: cd stf-rasp && yarn install && yarn eslint
