name: PR Web
on: [pull_request]

jobs:
  pr:
    runs-on: macos-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
          mongodb-replica-set: test-stf-db

      - name: Install dependency
        run: yarn install

      - name: Api
        run: cd stf-api && yarn test

      - name: Player
        run: cd stf-player && yarn eslint && yarn build

      - name: Admin
        run: cd stf-admin && yarn eslint && yarn build

      - name: Core
        run: cd stf-core && yarn eslint
